# Analysis params
ant_str: "0_1,0_3,0_5"
seed: 7123689
Niter: 1000
Nproc: 1
verbose: True
ps_prior_lo: 0.1
ps_prior_hi: 2
n_ps_prior_bins: 3
# Write params
dirname: "results-seed-7123689-Niter-1000"
clobber: False
# Signal model
sigcov0: "./test_data/eor-cov/"
sigcov0_file: "eor-cov.npy"
# FG model
Nfgmodes: 12
fgmodes: "./test_data/fgmodes/"
fgmodes_file: "fgmodes.npy"
# Noise
noise: "./test_data/noise/"
noise_file: "noise.npy"
noise_cov: "./test_data/noise/"
noise_cov_file: "noise-cov.npy"
# Input files
file_paths:
- "./test-data/vis-eor-fgs.uvh5"