# Analysis params
ant_str: all 
seed: 7123689
Niter: 5
Nproc: 1
verbose: True
ps_prior_lo: 0.1
ps_prior_hi: 2
n_ps_prior_bins: 3
# Write params
dirname: "results/strong_scaling/4096bl_16r"
clobber: False
# Signal model
sigcov0: "scaling-data/eor-cov/"
sigcov0_file: "eor-cov.npy"
# FG model
Nfgmodes: 12
fgmodes: "scaling-data/fgmodes/"
fgmodes_file: "fgmodes.npy"
# Noise
noise: "scaling-data/noise/"
noise_file: "noise.npy"
noise_cov: "scaling-data/noise/"
noise_cov_file: "noise-cov.npy"
# Input files
file_paths:
- "scaling-data/vis-eor-fgs.uvh5"
