# Analysis params
ant_str: "0_1,0_3,0_5"
seed: 7123689
Niter: 1000
Nproc: 1
verbose: False
ps_prior_lo: 0.1
ps_prior_hi: 2
n_ps_prior_bins: 3
# Write params
dirname: "results-seed-7123689-Niter-1000"
clobber: False
# Signal model
sigcov0: "./test-data/eor-cov/"
sigcov0_file: "cov.npy"
# FG model
Nfgmodes: 12
fg_eig_dir: "./test-data/fgmodes/"
fg_eig_file: "fgmodes.npy"
# Noise
noise: "./test-data/noise/"
noise_file: "noise.npy"
noise_cov: "./test-data/noise/"
noise_cov_file: "cov.npy"
# Input files
file_paths:
- "./test-data/vis-eor-fgs.uvh5"